In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('insurance.csv')

In [22]:
df['city'] = pakistan_cities = [
"Karachi","Lahore","Islamabad","Rawalpindi","Faisalabad",
"Multan","Peshawar","Quetta","Hyderabad","Gujranwala",
"Sialkot","Sargodha","Bahawalpur","Sukkur","Larkana",
"Sheikhupura","Gujrat","Sahiwal","Okara","Jhang",
"Rahim Yar Khan","Dera Ghazi Khan","Abbottabad","Mardan","Mingora",
"Nawabshah","Khuzdar","Turbat","Chaman","Gwadar",
"Haripur","Mansehra","Battagram","Kohat","Bannu",
"Lakki Marwat","Charsadda","Nowshera","Dera Ismail Khan","Zhob",
"Sibi","Hub","Umerkot","Thatta","Badin",
"Tando Adam","Tando Allahyar","Kotli","Mirpur","Gilgit",
"Skardu","Chilas","Hunza","Muzaffarabad","Bhakkar",
"Khushab","Mianwali","Attock","Jhelum","Chakwal",
"Kasur","Pakpattan","Vehari","Khanewal","Lodhran",
"Bahawalnagar","Hafizabad","Narowal","Shakargarh","Muridke",
"Kamoke","Wazirabad","Daska","Sambrial","Pasrur",
"Shikarpur","Jacobabad","Kandhkot","Ghotki","Kashmore",
"Khairpur","Tando Muhammad Khan","Sanghar","Matiari","Dadu",
"Sehwan","Kot Adu","Layyah","Taunsa","Chiniot",
"Toba Tek Singh","Jaranwala","Gojra","Kamalia","Fort Abbas",
"Taxila","Hangu","Timergara","Parachinar","Gakhar"
]

In [23]:
df

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category
0,67,119.8,1.56,2.92000,False,Karachi,retired,High
1,36,101.1,1.83,34.28000,False,Lahore,freelancer,Low
2,39,56.8,1.64,36.64000,False,Islamabad,freelancer,Low
3,22,109.4,1.55,3.34000,True,Rawalpindi,student,Medium
4,69,62.2,1.60,3.94000,True,Faisalabad,retired,High
...,...,...,...,...,...,...,...,...
95,36,52.8,1.57,19.64000,False,Taxila,business_owner,Low
96,26,113.8,1.54,34.01000,False,Hangu,private_job,Low
97,52,60.8,1.80,44.86000,False,Timergara,freelancer,Low
98,27,101.1,1.82,28.30000,False,Parachinar,business_owner,Low
99,40,70.0,1.59,28.16664,True,Gakhar,government_job,Low

In [24]:
df['bmi'] = round(df['weight'] / (df['height']**2), 2)

In [25]:
def age_group(age):
	if age < 25:
		return 'young'
	elif age < 45:
		return 'adult'
	elif age < 60:
		return 'middle_aged'
	else:
		return 'senior'
	
df['age_group'] = df['age'].apply(age_group)

In [28]:
tier_1_cities = ["Karachi","Lahore","Islamabad","Rawalpindi","Faisalabad","Gujranwala","Multan","Peshawar","Hyderabad","Quetta"]
tier_2_cities = ["Sialkot","Sargodha","Bahawalpur","Sukkur","Larkana","Sheikhupura","Gujrat","Sahiwal","Okara","Jhang","Rahim Yar Khan","Dera Ghazi Khan","Abbottabad","Mardan","Mingora","Nawabshah","Khuzdar","Turbat","Chaman","Gwadar"]

In [30]:
def city_tier(city):
    if city in tier_1_cities:
        return 1
    elif city in tier_2_cities:
        return 2
    else:
        return 3
    
df['city_tier'] = df['city'].apply(city_tier)

In [38]:
def lifestyle_risks(row):
    if row["smoker"] and row["bmi"] > 30:
        return "high"
    elif row["smoker"] or row["bmi"] > 27:
        return "medium"
    else:
        return "low"

df['lifestyle_risk'] = df.apply(lifestyle_risks, axis=1)

In [ ]:
df.drop(columns=['age', 'weight', 'height', 'smoker', 'city'], inplace=True)

,age,weight,height,income_lpa,smoker,city,occupation,insurance_premium_category,bmi,age_group,city_tier,lifestyle_risk
0,67,119.8,1.56,2.92000,False,Karachi,retired,High,49.23,senior,1,medium
1,36,101.1,1.83,34.28000,False,Lahore,freelancer,Low,30.19,adult,1,medium
2,39,56.8,1.64,36.64000,False,Islamabad,freelancer,Low,21.12,adult,1,low
3,22,109.4,1.55,3.34000,True,Rawalpindi,student,Medium,45.54,young,1,high
4,69,62.2,1.60,3.94000,True,Faisalabad,retired,High,24.30,senior,1,medium
...,...,...,...,...,...,...,...,...,...,...,...,...
95,36,52.8,1.57,19.64000,False,Taxila,business_owner,Low,21.42,adult,3,low
96,26,113.8,1.54,34.01000,False,Hangu,private_job,Low,47.98,adult,3,medium
97,52,60.8,1.80,44.86000,False,Timergara,freelancer,Low,18.77,middle_aged,3,low
98,27,101.1,1.82,28.30000,False,Parachinar,business_owner,Low,30.52,adult,3,medium
99,40,70.0,1.59,28.16664,True,Gakhar,government_job,Low,27.69,adult,3,medium